quotes/app_quotes/urls.py
from django.urls import path

from . import views


app_name = 'app_quotes'

urlpatterns = [
    path("", views.hello, name='home'),
    path("/quotes", views.index, name='quotes'),
    path("/quotes/<int:page>", views.index, name='quotes_paginate'),
    path("/author/<author_name>", views.author, name='author'),
    path("/add_author", views.add_author_to_db, name='add_author'),
    path("/add_quote", views.add_quote_to_db, name='add_quote'),
]

quotes/app_users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = "app_users"

urlpatterns = [
    path('/signup', views.signupuser, name='signup'),
    path('/login', views.loginuser, name='login'),
    path('/userlogout', views.logoutuser, name='userlogout'),
    path('/profile/', views.profile, name='profile'),
    path('/reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('/reset-password/done/', PasswordResetDoneView.as_view(template_name='app_users/password_reset_done.html'),
         name='password_reset_done'),
    path('/reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='app_users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('/reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='app_users/password_reset_complete.html'),
         name='password_reset_complete')
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include('app_quotes.urls')),
    path("/user", include('app_users.urls')),
    path("admin/", admin.site.urls),
    
]

quotes/app_quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=100)
    born_date = models.DateField()
    born_location = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.fullname

class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.TextField()
    tags = models.CharField(max_length=100)

    def __str__(self):
        return self.quote

quotes/app_quotes/forms.py
from django import forms
from .models import Author, Quote


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

quotes/app_quotes/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, Page
from mongoengine import connect


from .utils import Author, Quote
from .forms import AuthorForm, QuoteForm

connect(db='database', host="mongodb+srv://olesyashevchuk0402:JeJ6Bb00zAnOUTRL@cluster0.ki8cwf1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")

def hello(request):
    return render(request, 'app_quotes/index.html', context={"msg": "Hello in quotes website!"})

def index(request, page=1):
    quotes = Quote.objects.all()
    paginator = Paginator(quotes, 20)
    quotes_on_page = paginator.page(page)
    return render(request, 'app_quotes/quotes.html', context={'quotes_on_page': quotes_on_page})


def author(request, author_name):
    author = Author.objects.get(fullname=author_name)
    return render(request, 'app_quotes/author.html', context={"author": author})


@login_required
def add_author_to_db(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = Author(
                fullname=form.fullname,
                born_date=form.born_date,
                born_location=form.born_location,
                description=form.description
            )
            form.save()
            author.save()
            return redirect(to='app_quotes:quotes')
    else:
        form = AuthorForm()
    return render(request, 'app_quotes/add_author.html', {'form': form})

@login_required
def add_quote_to_db(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = Quote(
                quote=form.quote,
                author=form.author,
                tags=form.tags
            )
            form.save()
            quote.save()
            return redirect(to='app_quotes:quotes')
    else:
        form = QuoteForm()
    return render(request, 'app_quotes/add_quote.html', {'form': form})

quotes/app_quotes/templates/app_quotes/add_author.html
{% extends 'app_quotes/base.html' %}

{% block body %}
<form method="POST" action="{% url 'app_quotes:add_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author name:
            {{form.fullname}}
        </label>
        <span>{{form.errors.fullname}}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born date:
            {{form.born_date}}
        </label>
        <span>{{form.errors.born_date}}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born location:
            {{form.born_location}}
        </label>
        <span>{{form.errors.born_location}}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author description:
            {{form.description}}
        </label>
        <span>{{form.errors.description}}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/app_quotes/templates/app_quotes/add_quote.html
{% extends 'app_quotes/base.html' %}

{% block body %}
<form method="POST" action="{% url 'app_quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the quote:
            {{form.quote}}
        </label>
        <span>{{form.errors.quote}}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author:
            {{form.author}}
        </label>
        <span>{{form.errors.author}}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the tags:
            {{form.tags}}
        </label>
        <span>{{form.errors.tags}}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/app_quotes/templates/app_quotes/author.html
{% extends 'app_quotes/base.html' %}

{% block body %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong>
        <span class="author-born-date">{{author.born_date}}</span>
        <span class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description"> {{author.description}}         
    </div>
</div>

{% endblock %}

quotes/app_quotes/templates/app_quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_quotes/style.css'%}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'app_quotes:home' %}">Home</a>
                <a class="nav-link" href="{% url 'app_quotes:quotes' %}">Quotes</a>
                {% if user.is_authenticated %}
                <div class="d-flex"><a class="nav-link" href="{% url 'app_users:userlogout' %}">Logout</a></div>
                <div class="d-flex"><a class="nav-link" href="{% url 'app_quotes:add_author' %}">Add author</a></div>
                <div class="d-flex"><a class="nav-link" href="{% url 'app_quotes:add_quote' %}">Add quotes</a></div>

                {% else %}
                <a class="nav-link" href="{% url 'app_users:signup' %}">Register</a>
                <a class="nav-link" href="{% url 'app_users:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

quotes/app_quotes/templates/app_quotes/index.html
{% extends 'app_quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h1>{{msg}}</h1>
</div> 
{% endblock %}

quotes/app_quotes/templates/app_quotes/quotes.html
{% extends 'app_quotes/base.html' %}

{% block body %}

    <div class="row">
        <div class="col-md-8">
            {% for quote in quotes_on_page %}
            <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text"> {{quote.quote}} </span>
                <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'app_quotes:author' author_name=quote.author.fullname %}">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world" /    > 
                    {% for tag in quote.tags %}
                    <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <nav>
        <ul class="pager">
            
            <li class="previous">
                <a class="{% if not quotes_on_page.has_previous %} disabled {% endif %}"
                href="{% if quotes_on_page.has_previous %}{% url 'app_quotes:quotes_paginate' quotes_on_page.previous_page_number %} {% else %} # {% endif %}">
                <span aria-hidden="true">&larr;</span> Previous</a>
            </li>
            
            
            <li class="next">
                <a class="{% if not quotes_on_page.has_next %} disabled {% endif %}"
                href="{% if quotes_on_page.has_next %}{% url 'app_quotes:quotes_paginate' quotes_on_page.next_page_number %} {% else %} # {% endif %}">Next
                <span aria-hidden="true">&rarr;</span></a>
            </li>
            
        </ul>
    </nav>
    
{% endblock %}