quotes/app_users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = "app_users"

urlpatterns = [
    path('/signup', views.signupuser, name='signup'),
    path('/login', views.loginuser, name='login'),
    path('/userlogout', views.logoutuser, name='userlogout'),
    path('/profile/', views.profile, name='profile'),
    path('/reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('/reset-password/done/', PasswordResetDoneView.as_view(template_name='app_users/password_reset_done.html'),
         name='password_reset_done'),
    path('/reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='app_users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('/reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='app_users/password_reset_complete.html'),
         name='password_reset_complete')
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include('app_quotes.urls')),
    path("/user", include('app_users.urls')),
    path("admin/", admin.site.urls),
    
]

quotes/app_users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

quotes/app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    email = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

quotes/app_users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm, ProfileForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='app_quotes:quotes')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='app_quotes:quotes')
        else:
            return render(request, 'app_users/login.html', context={"form": form})

    return render(request, 'app_users/register.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
       return redirect(to='app_quotes:quotes')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='app_users:login')

        login(request, user)
        return redirect(to='app_quotes:quotes')

    return render(request, 'app_users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return render(request, 'app_users/logout.html', context={})

@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='app_users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'app_users/profile.html', {'profile_form': profile_form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'app_users/password_reset.html'
    email_template_name = 'app_users/password_reset_email.html'
    html_email_template_name = 'app_users/password_reset_email.html'
    success_url = reverse_lazy('app_users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'app_users/password_reset_subject.txt'
    

quotes/app_users/templates/app_users/login.html
{% extends 'app_quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
    <div class="small text-center">
        <a href="{% url 'app_users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</div>
{% endblock %}

quotes/app_users/templates/app_users/logout.html
{% extends 'app_quotes/base.html' %}

{% block body %}

    <div class="container mt-3">
        <h1>We look forward to seeing you again!</h1>
    </div>

{% endblock %}

quotes/app_users/templates/app_users/password_reset.html
{% extends 'app_quotes/base.html' %}

{% block body %}

    <h2>Password reset</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Request password reset</button>
    </form>

{% endblock %}

quotes/app_users/templates/app_users/password_reset_complete.html
{% extends 'app_quotes/base.html' %}

{% block body %}
<h2>Password reset complete!</h2>
{% endblock %}

quotes/app_users/templates/app_users/password_reset_confirm.html
{% extends 'app_quotes/base.html' %}

{% block body %}
<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>
{% endblock %}

quotes/app_users/templates/app_users/password_reset_done.html
{% extends 'app_quotes/base.html' %}

{% block body %}
<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>
{% endblock %}

quotes/app_users/templates/app_users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'app_users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'app_users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes/app_users/templates/app_users/register.html
{% extends 'app_quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div>
            <label> Email:
                {{ form.email }}
            </label>
            <span>{{ form.errors.email }}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}